# Generated by Django 4.1 on 2022-08-15 20:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25, verbose_name="Name")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("WC", "WILDCARD"),
                            ("DA", "DAIRY"),
                            ("PR", "PROTEIN"),
                            ("ST", "STAPLE"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "properties",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=17),
                        blank=True,
                        max_length=10,
                        size=None,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ingredient",
                "verbose_name_plural": "Ingredients",
                "ordering": ["name"],
            },
        ),
    ]
