# Generated by Django 4.1 on 2022-08-15 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Ingredients", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="ingredient", name="category",),
    ]
