# Generated by Django 4.1 on 2022-08-16 11:51

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("Ingredients", "0005_ingredient_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="category",
            field=models.CharField(
                choices=[
                    ("WC", "Wild Card"),
                    ("DA", "Dairy"),
                    ("PR", "Protein"),
                    ("ST", "Staple"),
                ],
                default="WC",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="properties",
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=models.CharField(max_length=3),
                blank=True,
                max_length=15,
                size=None,
            ),
        ),
    ]
