# Generated by Django 4.1 on 2022-08-16 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Ingredients", "0007_alter_ingredient_properties"),
    ]

    operations = [
        migrations.RemoveField(model_name="ingredient", name="category",),
        migrations.RemoveField(model_name="ingredient", name="properties",),
    ]
