# Generated by Django 4.1 on 2022-08-16 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Ingredients", "0008_remove_ingredient_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="category",
            field=models.CharField(
                choices=[
                    ("WC", "Wild Card"),
                    ("DA", "Dairy"),
                    ("PR", "Protein"),
                    ("ST", "Staple"),
                ],
                default="WC",
                max_length=2,
            ),
        ),
    ]
