# Generated by Django 4.1 on 2022-09-01 12:39

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("Ingredients", "0010_ingredient_properties"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="category",
            field=models.CharField(
                choices=[
                    ("WC", "Wild Card"),
                    ("DA", "Dairy"),
                    ("PR", "Protein"),
                    ("ST", "Staple"),
                    ("VE", "Vegetable"),
                    ("EX", "Extra"),
                    ("FR", "Fruit"),
                ],
                default="WC",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="properties",
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("SW", "Sweet"),
                        ("SP", "Spicy"),
                        ("VG", "Vegan"),
                        ("VE", "Vegetarian"),
                        ("DE", "Dessert"),
                        ("SA", "Salty"),
                        ("FI", "Fish"),
                        ("ME", "Meat"),
                        ("AP", "Animal Product"),
                        ("CO", "Condiment"),
                    ],
                    max_length=3,
                ),
                blank=True,
                default=list,
                max_length=15,
                size=None,
            ),
        ),
    ]
