# Generated by Django 4.1 on 2022-10-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Ingredients", "0013_alter_ingredient_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="image",
            field=models.ImageField(upload_to="ingredients/"),
        ),
    ]
